const ADD_ITEM = 'ADD_ITEM'
const RESET_CART = 'RESET_CART'
const DELETE_ITEM = 'DELETE_ITEM'
const COMPONENT_UPDATE = 'COMPONENT_UPDATE'

export default {
    ADD_ITEM,
    RESET_CART,
    DELETE_ITEM,
    COMPONENT_UPDATE
}